-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHaDVPe2I9Q4Hnoqp
8sfmN4ALLISKuiBNQAE7K/NhHYWgCgYIKoZIzj0DAQehRANCAAQ8BN/RKr2SvceE
yPO2CwXcLIdyagdUUccYd2uVdywjHlAKV7EIikDyLqCyLqqhoiivSoizE0fZXo69
G43Tk9Tn
-----END PRIVATE KEY-----